
logging:
  level:
    root: info
  config: classpath:logback-ctx.xml
  file: F:/cache/logs

server:
  port: 8080

mysql:
  host: localhost
  port: 3306
  database: crown
  username: root
  password: root
