
logging:
  level:
    root: info
  config: classpath:logback-ctx.xml
  file: f:/cache/logs


server:
  port: 8088
  servlet:
    context-path: "/@project.artifactId@"

mysql:
  host: localhost
  port: 3306
  database: crown
  username: root
  password: root
